export const routes = {
  home: "/",
  auth: {
    root: "/auth",
    signup: "signup",
    client: "client",
    business: "business",
    signin: "signin",
    createNewPassword: "create-new-password",
  },
  settings: {
    root: "/settings",
    appointments: "appointments",
    clients: {
      root: "clients",
      add: "add",
    },
    businessProfile: "business-profile",
    units: {
      root: "units",
      add: {
        root: "add",
        tab: ":tab",
        general: "general",
        portfolio: "portfolio",
        certificates: "certificates",
        reviews: "reviews",
        schedule: "schedule",
        staff: "staff",
      },
      edit: {
        root: "edit",
        unitId: {
          root: ":unitId",
          tab: ":tab",
          general: "general",
          portfolio: "portfolio",
          certificates: "certificates",
          reviews: "reviews",
          schedule: "schedule",
          staff: "staff",
        },
      },
    },
    staff: {
      root: "staff-members",
      add: {
        root: "add",
        tab: ":tab",
        general: "general",
        services: "services",
        portfolio: "portfolio",
        certificates: "certificates",
        reviews: "reviews",
        schedule: "schedule",
      },
      edit: {
        root: "edit",
        masterId: {
          root: ":masterId",
          tab: ":tab",
          general: "general",
          services: "services",
          portfolio: "portfolio",
          certificates: "certificates",
          reviews: "reviews",
          schedule: "schedule",
        },
      },
    },
    services: "business-services",
  },
  calendar: "/calendar",
  services: "/services",
  finances: "/finances",
  about: "/about",
  contacts: "/contacts",
  howitworks: "/howitworks",
  policy: "/policy",
  service: "/service",
  landing: {
    root: "/landing",
    units: {
      root: "units",
    },
    unitId: "/:unitId",
  },
};
