# Сначала, используем официальный образ Node.js для сборки фронтенда
FROM node:20 

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы package.json и package-lock.json в контейнер
COPY    package*.json       ./

# Устанавливаем зависимости
RUN     npm install

# Копируем все файлы проекта в контейнер
COPY    .  .

# Запускаем сборку
RUN     npm run build

CMD ["npm", "start"]


# Второй этап сборки, используем nginx для создания production-ready образа
#FROM nginx:alpine

# Копируем собранные файлы из предыдущего этапа в новый контейнер
#COPY --from=builder     /app/build      /usr/share/nginx/html

# Опционально, можно добавить кастомные конфигурации nginx, если это необходимо
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Опционально, можно указать порт, на котором будет работать nginx
# EXPOSE 80

# Команда, которая будет запускаться при запуске контейнера
# CMD ["nginx", "-g", "daemon off;"]