FROM nginx:alpine

COPY    ./nginx.conf       /etc/nginx/conf.d/default.conf

COPY    ./build            /usr/share/nginx/html



# Опционально, можно указать порт, на котором будет работать nginx
# EXPOSE 80

# Команда, которая будет запускаться при запуске контейнера
# CMD ["nginx", "-g", "daemon off;"]